### PR TITLE
sound: reconnect to pa

### LINKED ISSUE #334: Reconnection to pulseaudio
How to reproduce: run i3status-rust with the following config and then run `pulseaudio -k`.

```toml
[[block]]
block = "sound"
```

Pulseaudio is restarted (since it a normal behavior for a daemon), but no reconnection is made. I don't really know, is it a significant issue, since it can be fixed with an i3 restarting. But still no notes that something went wrong.

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Fixes #334

Ideally this should be reflected in the UI, but for now I suppose it is better than just stalling the block.

Also, apparently there is a bug in `libpulse_binding` as it is possible to segfault w/o `unsafe`.

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Is lowlevel PA protocol documented? Is there something like https://wayland-book.com/protocol-design/wire-protocol.html but for pulseaudio?

File: src/blocks/sound/pulseaudio.rs [hunk 1]
```diff
@@ -182,78 +198,106 @@ impl Connection {
 impl Client {
     fn new() -> Result<Client> {
         let (send_req, recv_req) = unbounded();
+        let (wake_rx, wake_tx) = nix::unistd::pipe().unwrap();
+
+        extern "C" fn wake_cb(
```
Comment (bim9262) [inline src/blocks/sound/pulseaudio.rs:203]: Could you add some comments from here through line 210? I found it pretty difficult to appreciate what's happening.

**Comment by bim9262** [comment]
While I wasn't able to grok lines 201-210 the change looked good overall and my preliminary testing looks good too. Now if only players I use would also reconnect...

File: src/blocks/sound/pulseaudio.rs (hunk 1 above)
Comment (MaxVerevkin) [reply src/blocks/sound/pulseaudio.rs:203]: Yeah, sure! I will probably refactor this code into something like `struct MainloopWaker`.
