### PR TITLE
Fix #89 support running a block only once

### LINKED ISSUE #89: make custom block command run once
Hello! I am trying to make a block to run only once. I do not know if this is an issue or something i do wrong.

I have this block
[[block]]
block = "custom"
interval = 60
command = "cat /tmp/.email"
on_click = 'python ~/.config/i3/mutt.py'

mutt.py:
import filelock
import os
import sys
import time
parentpid = os.getpid()
lock = filelock.FileLock("/tmp/.mutt_runnning_lock")
try:
    with lock.acquire(timeout = .1):
        pid = os.fork()
        os.kill(parentpid,9)
        os.system('termite -e "mutt";~/bin/checkMail.sh &')
        lock.release()
except:
    exit(0)

what the script does is create a a lockfile. if lockfile can not be acquired it exits.

Problem: when i click multiple times on the block it opens many termite with mutt many times.
When I run the script multiple times from the shell it seems to do what it is supposed to: if mutt is open it does not open multiple instances

### PR DESCRIPTION
**Pull request by PicoJr**
Fix #89 

```toml
interval = 2  # every 2 seconds
```
```toml
interval = "once" # only update once
```
```toml
# interval not provided, use default value
```

This PR modifies the `Block` trait and adds an `Update` enum:

```diff
    /// Forces an update of the internal state of the block.
-    fn update(&mut self) -> Result<Option<Duration>> {
+    fn update(&mut self) -> Result<Option<Update>> {
```

```rust
pub enum Update {
    Every(Duration), // update every <duration> seconds
    Once, // only update once
}
```

What do you think?

## How to try this PR

status.toml:

```toml
[[block]]
block = "custom"
command = "date"
interval = 2 # updated every 2 seconds

[[block]]
block = "custom"
command = "date"
interval = "once" # only updated once

[[block]]
block = "custom"
command = "date"
# no interval provided, updated every 10 seconds
```

`./target/debug/i3status-rs test.toml`

Then check the first block is updated every 2 seconds, the 2nd block only once and 3rd block every 10 seconds.

## TODO before merge

- [x] rebase
- [x] rename `Refresh` to `Update` ?
- [x] add doc
- [x] does it make sense to support running once for other blocks?

### CODE REVIEW

File: src/blocks.rs [hunk 1]
```diff
@@ -76,6 +76,24 @@ use crate::input::I3BarEvent;
 use crate::scheduler::Task;
 use crate::widget::I3BarWidget;
 
+#[derive(Clone, Debug, PartialEq)]
+pub enum Refresh {
```
Comment (ammgws) [inline src/blocks.rs:80]: If we go with this then perhaps Update might be better, as you mentioned.

Comment (PicoJr) [reply src/blocks.rs:80]: I'll rename `Refresh` to `Update` then =)

File: blocks.md [hunk 2]
```diff
@@ -218,7 +233,7 @@ Key | Values | Required | Default
 `command` | Shell command to execute & display. | No | None
 `on_click` | Command to execute when the button is clicked. The command will be passed to whatever is specified in your `$SHELL` variable and - if not set - fallback to `sh`. | No | None
 `cycle` | Commands to execute and change when the button is clicked. | No | None
-`interval` | Update interval, in seconds. | No | `10`
+`interval` | Update interval, in seconds (or `"once"` or `"Once"` to update only once). | No | `10`
```
Comment (ammgws) [inline blocks.md:236]: Let's just go with "once".

Comment (PicoJr) [reply blocks.md]: Sure =)

**Comment by ammgws** [comment]
> does it make sense to support running once for other blocks?

| Block | Has update interval? | Run once sensible? |
| ---- | ----| ----|
|Backlight | no | - |
|Battery|yes| no |
|Bluetooth|no| -|
|CPU Utilization|yes|no|
|Custom| yes | yes |
|Custom DBus|no | - |
|Disk Space| yes | maybe |
|Focused Window|no | - |
|IBus| no | - |
|Keyboard Layout| yes | maybe |
|Load| yes | no |
|Maildir|yes | no |
|Memory| yes | no |
|Music| no | - |
|Net| yes | no |
|NetworkManager| no | - |
|Notmuch| yes | no |
|Nvidia Gpu| yes | maybe |
|Pacman| yes | no |
|Pomodoro |yes | no |
|Sound| yes | no |
|Speed Test| yes | maybe |
|Taskwarrior|yes | no |
|Temperature| yes | no |
|Time| yes | no |
|Toggle|yes | yes |
| Uptime | yes | no |
|Watson| yes | no |
|Weather|yes | maybe |
|Xrandr| yes | maybe |

**Comment by ammgws** [comment]
I was mulling whether we should go with a mixed keyword/numeric option like you've proposed here or just purely numeric based with `-1` representing "run once". However I just checked i3blocks and they use mixed so I guess it's OK. If we ever introduce any other interval modes, having a named option would be better than trying to remember what `-2` means.

i3blocks interval options:
- \<non-zero number\>
- `-1` or `once`
- `-2` or `repeat`
- `-3` or `persist`

**Comment by PicoJr** [comment]
Thanks for your feedback: I'll rebase and resolve conflicts.
