### PR TITLE
Fix `.eng` formatter: inconsistent rounding

### LINKED ISSUE #1933: `.eng` formatter: inconsistent rounding
Format | Value
-----------|-----------
`$mem_total.eng(p:Mi,w:5)` | :heavy_check_mark: `14.96GiB`
`$mem_total.eng(p:Mi,w:4)` | :heavy_check_mark: `15.0GiB`
`$mem_total.eng(p:Mi,w:3)` | :heavy_check_mark: ` 15GiB`
`$mem_total.eng(p:Mi,w:2)` | :x: `14GiB`

### PR DESCRIPTION
**Pull request by bim9262**
Fixes #1933

### CODE REVIEW

File: src/formatting/formatter.rs [hunk 1]
```diff
@@ -616,7 +615,7 @@ mod tests {
                 &config,
             )
             .unwrap();
-        assert_eq!(result, "999B");
+        assert_eq!(result, "1.0KB");
```
Comment (bim9262) [inline src/formatting/formatter.rs:618]: What are the rules if this should be `" 1KB"` or `"1.0KB"`? Try to eliminate trailing zeros?

Comment (bim9262) [reply src/formatting/formatter.rs:618]: Actually `1.0KB` is consistent with these formats:

Format | Value
-- | --
`$mem_total.eng(p:Mi,w:5)` | `14.96GiB`
`$mem_total.eng(p:Mi,w:4)` | `15.0GiB`
`$mem_total.eng(p:Mi,w:3)` | ` 15GiB`
`$mem_total.eng(p:Mi,w:2)` | `15GiB`

So I think this is good as-is.

**Review by MaxVerevkin — APPROVED** [review]
Looks good to me.

By the way, great that you added these tests. We can make them a bit more compact with a macro like

```rust
macro_rules! fmt {
    ($name:ident, $($key:ident : $value:tt),*) => {
        new_formatter(stringify!($name), &[
            $( Arg { key: stringify!($key), val: stringify!($value) } ),*
        ]).unwrap()
    };
}
```

so that

```rust
let fmt = new_formatter(
    "eng",
    &[
        Arg { key: "w", val: "3" },
        Arg {
            key: "p",
            val: "Mi",
        },
    ],
)
.unwrap();
```

becomes

```rust
let fmt = fmt!(eng,w:3,p:Mi);
```
