### PR TITLE
Fail if click handler refers to unknown button

### LINKED ISSUE #1918: Invalid `button` in a click handler does not result in an error
```toml
[[block.click]]
button = "nonexisting"
```

does not error, it it probably should.

### PR DESCRIPTION
**Pull request by MaxVerevkin**
Fixes #1918

### CODE REVIEW

**Comment by MaxVerevkin** [comment]
Technically a breaking change but realistically it should be okay.

File: src/protocol/i3bar_event.rs [hunk 1]
```diff
@@ -37,7 +37,7 @@ fn unprocessed_events_stream(invert_scrolling: bool) -> BoxedStream<I3BarEvent>
             #[derive(Deserialize)]
             struct I3BarEventRaw {
                 instance: Option<String>,
-                button: MouseButton,
+                button: i64,
```
Comment (bim9262) [inline src/protocol/i3bar_event.rs:40]: What's the benefit of using an i64 instead of keeping it as a `MouseButton`?

Comment (MaxVerevkin) [reply src/protocol/i3bar_event.rs:40]: I wanted to handle the case in which bar sends a click event with button we don't support / know about. Now I see that is it better to leave this as a `MouseButton` and gracefully handle deserialization errors instead of unwrapping.

**Review by bim9262 — APPROVED** [review]
Looks good :)
