### PR TITLE
fixed pacman printing to stdout/err

### LINKED ISSUE #1214: pacman block prevents use
```toml
[[block]]
block = "pacman"
interval = 300
format_up_to_date = "0"
critical_updates_regex = "(linux|linux-lts|linux-zen|linux-ck|firefox|sudo|librewolf|linux-amd|firefox)"
```
causes invalid i3bar-json because the output of the pacman DB update is not piped away. Causing output similar to this:
```json
{"version": 1, "click_events": true}
:: Paketdatenbanken werden synchronisiert …
Fehler: failed to synchronize all databases (Kann Datenbank nicht sperren)
[[{"background":null,"color":"#424242","full_text…
```

If I read the source correct then it should put the database in `/tmp`, since it is tmpfs potential issues should be resolved after a restart, but they are not.

### PR DESCRIPTION
**Pull request by poldi1405**
This should fix #1214

### CODE REVIEW

File: src/blocks/pacman.rs [hunk 1]
```diff
@@ -264,7 +266,7 @@ fn get_pacman_available_updates() -> Result<String> {
             .env("LC_ALL", "C")
             .args(&[
                 "-c",
-                &format!("fakeroot pacman -Qu --dbpath \"{}\"", updates_db),
+                &format!("pacman -Qu --dbpath \"{}\"", updates_db),
```
Comment (ammgws) [inline src/blocks/pacman.rs:269]: Why remove fakeroot here?

File: src/blocks/pacman.rs [hunk 2]
```diff
@@ -254,7 +256,7 @@ fn get_pacman_available_updates() -> Result<String> {
 
     // Update database
     run_command(&format!(
-        "fakeroot -- pacman -Sy --dbpath \"{}\" --logfile /dev/null &> /dev/null",
+        "pacman -Sy --dbpath \"{}\"",
```
Comment (ammgws) [inline src/blocks/pacman.rs:259]: I'm not sure why we had `--logfile /dev/null` in the first place, but do you really need to remove it to fix your issue? If not then might be better to leave it for now, and perhaps remove it later once it's proven that it is really not needed.

**Review by ammgws — CHANGES_REQUESTED** [review]

File: src/blocks/pacman.rs (hunk 1 above)
Comment (poldi1405) [reply src/blocks/pacman.rs:269]: Instead of calling it through a shell which brings no advantage to my knowledge

File: src/blocks/pacman.rs (hunk 2 above)
Comment (poldi1405) [reply src/blocks/pacman.rs:259]: all output is discarded anyways and this just keeps the command simpler

File: src/blocks/pacman.rs (hunk 1 above)
Comment (ammgws) [reply src/blocks/pacman.rs:269]: Oh sorry I missed that fakeroot was moved to the other function. That function is kinda useless since it's only used in one place but that's another issue.

File: src/blocks/pacman.rs (hunk 2 above)
Comment (poldi1405) [reply src/blocks/pacman.rs:259]: > do you really need to remove it to fix your issue

technically I don't but since I was there I just did since it had no effect.

Comment (ammgws) [reply src/blocks/pacman.rs:259]: OK so it looks like we're just doing exactly what the `checkupdates` script does, so I would prefer to keep it for now even though it doesn't appear to be needed. There might be some weird issue that it solves.

File: src/blocks/pacman.rs [hunk 3]
```diff
@@ -192,8 +192,10 @@ impl ConfigBlock for Pacman {
 }
 
 fn run_command(var: &str) -> Result<()> {
-    Command::new("sh")
-        .args(&["-c", var])
+    Command::new("fakeroot")
+        .args(&["--", var])
+        .stdout(Stdio::null())
+        .stderr(Stdio::null())
```
Comment (MaxVerevkin) [inline src/blocks/pacman.rs:198]: Maybe leave `stderr` piped? If something is printed to `stderr` it doesn't break the bar, but might (?) be useful for debugging.

Comment (poldi1405) [reply src/blocks/pacman.rs:198]: sounds logical. Will do.

**Comment by ammgws** [comment]
Just need to run rustfmt on it.

**Comment by ammgws** [comment]
Thanks!
